/* Sums generated by sequences given by:
 *
 *   1. a1 + a2 + a1*a2 -- primes-1
 *   2. a1*a2 + a2*a3 + a1*a3 -- A025052
 *
 *   a1, a2, a3 an integer >= 1
 */
#include <stdio.h>

typedef unsigned long long int u64;

static char v[(1 << 24)];

static void clear_seq (void)
{
    int i;

    for (i = 0; i < sizeof(v); i++)
        v[i] = 0;
}

static void dump_seq (char *pfx, int n, int x)
{
    int i;

    printf("\nSEQ: %s\n", pfx);
    for (i = 1; i <= n; i++)
        if (v[i] == x)
            printf("%d ", i);
    printf("\n");
}

static void seq1 (void)
{
    int a1, a2;

    for (a1 = 1; a1 <= 200; a1++) {
        for (a2 = a1; a2 <= 200; a2++) {
            v[a1 + a2 + a1*a2] = 1;
        }
    }
}

static void seq2 (void)
{
    int a, b, c;

    for (a = 1; a <= 50; a++) {
        for (b = a; b <= 50; b++) {
            for (c = b; c <= 50; c++) {
                v[a*b+b*c+c*a] = 1;
            }
        }
    }
}

static void seq3 (void)
{
    int a, b, c, d;

    for (a = 1; a <= 150; a++) {
        for (b = a; b <= 150; b++) {
            for (c = b; c <= 150; c++) {
                for (d = c; d <= 150; d++) {
                    v[a*b + a*c + a*d + b*c + b*d + c*d] = 1;
                }
            }
        }
    }
}

/* a1*a2 + a2*a3 + a3*a4 + a4*a1: All composites are representable
 * (and all primes are not?)
 */
static void seq4 (void)
{
    int a, b, c, d;

    for (a = 1; a <= 200; a++) {
        for (b = a; b <= 200; b++) {
            for (c = b; c <= 200; c++) {
                for (d = c; d <= 200; d++) {
                    v[a*b + b*c + c*d + d*a] = 1;
                }
            }
        }
    }
}

static void seq5 (void)
{
    int a, b, c;
    u64 E;

    for (a = 1; a <= 1024; a++) {
        for (b = a; b <= 1024; b++) {
            if (a*b > (1 << 16)) break;
            for (c = b; c <= 1024; c++) {
                E = a + b + c + a*b + a*c + b*c + a*b*c;
                if (E >= (1 << 16)) break;
                v[E] = 1;
            }
        }
    }
}

/* abc+abd+acd+bcd: matches with A027563 */
static void seq6 (void)
{
    int a1, a2, a3, a4;
    u64 e;

    for (a1 = 1; a1 <= 1024; a1++) {
        for (a2 = a1; a2 <= 1024; a2++) {
            if (a1*a2 >= (1 << 16)) break;
            for (a3 = a2; a3 <= 1024; a3++) {
                if (a3*a1 >= (1 << 16)) break;
                if (a3*a2 >= (1 << 16)) break;
                for (a4 = a3; a4 <= 1024; a4++) {
                    e = a1*a2*a3 + a1*a2*a4 + a2*a3*a4 + a1*a3*a4;
                    if (e >= (1 << 14)) break;
                    v[e] = 1;
                }
            }
        }
    }
}

/* abcd+abce+abde+acde+bcde */
static void seq7 (void)
{
    int a, b, c, d, e;
    u64 E;

    for (a = 1; a <= 1024; a++) {
        for (b = a; b <= 1024; b++) {
            if (a*b >= (1 << 16)) break;
            for (c = b; c <= 1024; c++) {
                if (a*b*c >= (1 << 16)) break;
                for (d = c; d <= 1024; d++) {
                    if (a*b*c*d >= (1 << 16)) break;
                    for (e = d; e <= 1024; e++) {
                        E = a*b*c*d + a*b*c*e + a*b*d*e + a*c*d*e + b*c*d*e;
                        if (E >= (1 << 16)) break;
                        v[E] = 1;
                    }
                }
            }
        }
    }
}

static void seq8 (void)
{
    int a, b, c, d;
    u64 E;

    for (a = 1; a <= 1024; a++) {
        for (b = a; b <= 1024; b++) {
            if (a*b >= (1 << 16)) break;
            for (c = b; c <= 1024; c++) {
                if (a*b*c >= (1 << 16)) break;
                for (d = c; d <= 1024; d++) {
                    E = a + b + c + d +
                        a*b + b*c + c*d + d*a +
                        a*b*c + b*c*d + c*d*a + d*a*b +
                        a*b*c*d;
                    if (E >= (1 << 16)) break;
                    v[E] = 1;
                }
            }
        }
    }
}

static void seq9 (void)
{
    int a, b, c, d, e;
    u64 E;

    for (a = 1; a <= 1024; a++) {
        for (b = a; b <= 1024; b++) {
            if (a*b >= (1 << 16)) break;
            for (c = b; c <= 1024; c++) {
                if (a*b*c >= (1 << 16)) break;
                for (d = c; d <= 1024; d++) {
                    if (b*c*d >= (1 << 16)) break;
                    for (e = d; e <= 1024; e++) {
                        E = a*b*c + a*b*e + a*d*e + b*c*d + c*d*e;
                        if (E >= (1 << 16)) break;
                        v[E] = 1;
                    }
                }
            }
        }
    }
}

int main (int argc, char *argv[])
{
    clear_seq();
    seq1();
    dump_seq("a+b+ab", 300, 0);

    clear_seq();
    seq2();
    dump_seq("ab+bc+ac", 1024, 0);

    clear_seq();
    seq3();
    dump_seq("ab+ac+ad+bc+bd+cd", 1024, 0);

    clear_seq();
    seq4();
    dump_seq("ab+bc+cd+da", 500, 0);

    clear_seq();
    seq5();
    dump_seq("a+b+c+ab+bc+ca+abc", 300, 0);

    clear_seq();
    seq6();
    dump_seq("abc+abd+acd+bcd", 4096, 0);

    clear_seq();
    seq7();
    dump_seq("abcd+abce+abde+acde+bcde", 500, 0);

    clear_seq();
    seq8();
    dump_seq("a+b+c+d+ab+bc+cd+da+abc+bcd+cda+dab+abcd", 500, 0);

    clear_seq();
    seq9();
    dump_seq("abc+bcd+cde+dea+eab", 500, 0);

    return 0;
}
